### ISSUE TITLE
Django 5.x compatibility

### ISSUE THREAD

**Issue by lordoffreaks** [just-work/django-sitemap-generate#59]
Any plans on this? is there something that could be done to help?

**Comment by tumb1er** [comment]
Hello, no plans for it now.
But if you need a release, you may help with simple but time consuming maintenance tasks:

* Drop python versions that are not supported by GH actions anymore
* Add new python/django combinations in Tox config
* Make all checks green, if necessary
* Update PyPI info (requirements and classifiers) in setup.py
* Create contributors file ;)

I'll help with actual release and github config not related to code changes (tokens etc...)

**Comment by tumb1er** [comment]
https://pypi.org/project/django-sitemap-generate/0.7.0/

Thanks!
